### Neste código construiremos 3 redes neurais para aproximar derivadas.
### Nos meus testes os resultados foram positivos, mas não posso garantir a consistência dos resultados devido a aleatoriedade do conjunto de dados criado.

In [1]:
import tensorflow as tf
import numpy as np

float_pres='float64'

In [2]:
# Criando conjunto de dados

data_x_list=[]
data_y_list=[]
pi=np.pi

for i in range(50000):
    Δx = 0.01                                 # Distância espacial dos pontos na malha utilizada
    x = tf.range(-2, 2, Δx, dtype=float_pres) # Gerando a malha de pontos no espaço unidimensional
    
    # Gerando uma condição inicial aleatória
    #------------------------------------------------------------------------------------------------------------------
    k1 = tf.random.uniform([1], 0, 20, dtype='int32')   # Amostrando uma frequência aleatória para a função seno
    k1 = tf.cast(k1, dtype=float_pres)                  # Mudando o tipo do tensor
    k2 = tf.random.uniform([1], 0, 20, dtype='int32')   # Amostrando uma frequência aleatória para a função seno
    k2 = tf.cast(k2, dtype=float_pres)                  # Mudando o tipo do tensor
    a  = tf.random.uniform([1], 0, 1, dtype=float_pres) # Amostrando um peso aleatória para ponderar as funções seno
    b  = tf.random.uniform([1], 0, 2, dtype=float_pres) # Amostrando um modificador de amplitude aleatório
    #------------------------------------------------------------------------------------------------------------------
    
    # Valor da função
    u1 =     a * tf.expand_dims(tf.math.sin(k1*pi*x), axis=0) # Gerando pontos de acordo com a primeira função seno
    u2 = (1-a) * tf.expand_dims(tf.math.sin(k2*pi*x), axis=0) # Gerando pontos de acordo com a segunda função seno
    
    # Valor da derivada
    du1= a*k1*pi*tf.expand_dims(tf.math.cos(k1*pi*x), axis=0)
    du2= (1-a)*k2*pi*tf.expand_dims(tf.math.cos(k2*pi*x), axis=0)
    
    u = b*(u1+u2) 
    du= b*(du1+du2)
    
    data_x_list.append(u)
    data_y_list.append(du)

data_x=tf.concat(data_x_list,axis=0)
data_y=tf.concat(data_y_list,axis=0)

train_x=data_x[:40000]
train_y=data_y[:40000]
test_x=data_x[-40000:]
test_y=data_y[-40000:]

In [3]:
# Criando um modelo sequencial
model_foward=tf.keras.models.Sequential()

# Adicionando camadas
model_foward.add(tf.keras.layers.Reshape([400,1])) # A camada de convolução exige uma dimensão extra para a "cor" da imagem,
                                            # por isso o reshape para transformar o tensor de tamanho n x 400 em um tensor de tamanho n x 400 x 1
model_foward.add(tf.keras.layers.Conv1D(filters=1,activation='linear', kernel_size=2, use_bias=False,dtype=float_pres)) # Camada de convolução com ativação linear, após a convolução, a dimensão do vetor será n x 399.
                                                                                                       # Lembrando que, se temos um input com dimensão n x s x r e uma convolução com filtro a x b (a é o tamanho do kernel e b é a quantidade de filtros) 
                                                                                                       # Então o output da convolução será: n x (s-a+1) x b
                                                                                                       # Dada a natureza do problema, sabemos que não é necessário um bias (use_bias=False), então removemos ele para evitar overfitting.
model_foward.add(tf.keras.layers.Flatten()) # Esta camada remove a dimensão extra, transformando um tensor de tamanho n x 399 x 1 em um tensor de tamanho n x 399


optimizer = tf.keras.optimizers.Adam(learning_rate=10**-1, beta_1=0.9, beta_2=0.999, clipnorm=1.0)
model_foward.compile(loss='mean_squared_error',optimizer=optimizer,metrics=['mean_squared_error'])

In [4]:
history = model_foward.fit(train_x, train_y[:,:-1], # Como estamos calculando a derivada "pra frente", devemos remover a última derivada
                           batch_size=512,
                           epochs=30,
                           validation_split=0.2)
test_scores = model_foward.evaluate(test_x, test_y[:,:-1], verbose=1)
print('Test loss:', test_scores[0])
print('Test accuracy:', test_scores[1])

Epoch 1/30
63/63 [==============================] - 3s 10ms/step - loss: 523.7717 - mean_squared_error: 523.7717 - val_loss: 492.3479 - val_mean_squared_error: 492.3479
Epoch 2/30
63/63 [==============================] - 0s 6ms/step - loss: 460.4821 - mean_squared_error: 460.4821 - val_loss: 431.0152 - val_mean_squared_error: 431.0152
Epoch 3/30
63/63 [==============================] - 0s 6ms/step - loss: 401.4950 - mean_squared_error: 401.4950 - val_loss: 373.8777 - val_mean_squared_error: 373.8777
Epoch 4/30
63/63 [==============================] - 0s 6ms/step - loss: 346.4859 - mean_squared_error: 346.4859 - val_loss: 320.9509 - val_mean_squared_error: 320.9509
Epoch 5/30
63/63 [==============================] - 0s 6ms/step - loss: 295.8019 - mean_squared_error: 295.8019 - val_loss: 272.2405 - val_mean_squared_error: 272.2405
Epoch 6/30
63/63 [==============================] - 0s 6ms/step - loss: 249.5627 - mean_squared_error: 249.5627 - val_loss: 227.7016 - val_mean_squared_error: 

In [5]:
# Pegando os pesos da segunda camada (a de convolução) da rede e multiplicando por Δx para ver se o valor está correto (o ideal seria -1 e 1).
model_foward.layers[1].weights[0]*Δx

<tf.Tensor: shape=(2, 1, 1), dtype=float64, numpy=
array([[[-0.95007384]],

       [[ 1.01301466]]])>

In [6]:
# Criando um modelo sequencial
model_backward=tf.keras.models.Sequential()

# Adicionando camadas
model_backward.add(tf.keras.layers.Reshape([400,1])) # A camada de convolução exige uma dimensão extra para a "cor" da imagem,
                                            # por isso o reshape para transformar o tensor de tamanho n x 400 em um tensor de tamanho n x 400 x 1
model_backward.add(tf.keras.layers.Conv1D(filters=1,activation='linear', kernel_size=2, use_bias=False)) # Camada de convolução com ativação linear, após a convolução, a dimensão do vetor será n x 399.
                                                                                                         # Lembrando que, se temos um input com dimensão n x s x r e uma convolução com filtro a x b (a é o tamanho do kernel e b é a quantidade de filtros) 
                                                                                                         # Então o output da convolução será: n x (s-a+1) x b
model_backward.add(tf.keras.layers.Flatten()) # Esta camada remove a dimensão extra, transformando um tensor de tamanho n x 399 x 1 em um tensor de tamanho n x 399


optimizer = tf.keras.optimizers.Adam(learning_rate=10**-1, beta_1=0.9, beta_2=0.999, clipnorm=1.0)
model_backward.compile(loss='mean_squared_error',optimizer=optimizer,metrics=['mean_squared_error'])

In [7]:
history = model_backward.fit(train_x, train_y[:,1:], # Como estamos calculando a derivada "pra trás", devemos remover a primeira derivada
                    batch_size=512,
                    epochs=30,
                    validation_split=0.2)
test_scores = model_backward.evaluate(test_x, test_y[:,1:], verbose=1)
print('Test loss:', test_scores[0])
print('Test accuracy:', test_scores[1])

Epoch 1/30
63/63 [==============================] - 1s 9ms/step - loss: 525.5174 - mean_squared_error: 525.5174 - val_loss: 494.0469 - val_mean_squared_error: 494.0469
Epoch 2/30
63/63 [==============================] - 0s 6ms/step - loss: 462.0206 - mean_squared_error: 462.0206 - val_loss: 432.6075 - val_mean_squared_error: 432.6075
Epoch 3/30
63/63 [==============================] - 0s 6ms/step - loss: 403.1559 - mean_squared_error: 403.1559 - val_loss: 375.3908 - val_mean_squared_error: 375.3908
Epoch 4/30
63/63 [==============================] - 0s 5ms/step - loss: 348.0058 - mean_squared_error: 348.0058 - val_loss: 322.3504 - val_mean_squared_error: 322.3504
Epoch 5/30
63/63 [==============================] - 0s 6ms/step - loss: 297.1942 - mean_squared_error: 297.1942 - val_loss: 273.5144 - val_mean_squared_error: 273.5144
Epoch 6/30
63/63 [==============================] - 0s 6ms/step - loss: 250.6385 - mean_squared_error: 250.6385 - val_loss: 228.9058 - val_mean_squared_error: 2

In [8]:
# Pegando os pesos da segunda camada (a de convolução) da rede e multiplicando por Δx para ver se o valor está correto (o ideal seria -1 e 1).
model_backward.layers[1].weights[0]*Δx

<tf.Tensor: shape=(2, 1, 1), dtype=float32, numpy=
array([[[-1.0124806 ]],

       [[ 0.95030844]]], dtype=float32)>

In [9]:
# Criando um modelo sequencial
model_middle=tf.keras.models.Sequential()

# Adicionando camadas
model_middle.add(tf.keras.layers.Reshape([400,1])) # A camada de convolução exige uma dimensão extra para a "cor" da imagem,
                                            # por isso o reshape para transformar o tensor de tamanho n x 400 em um tensor de tamanho n x 400 x 1
# Observe que, para a derivada centrada, o kernel_size deve ser 3.
model_middle.add(tf.keras.layers.Conv1D(filters=1,activation='linear', kernel_size=3, use_bias=False)) # Camada de convolução com ativação linear, após a convolução, a dimensão do vetor será n x 398.
                                                                                                       # Lembrando que, se temos um input com dimensão n x s x r e uma convolução com filtro a x b (a é o tamanho do kernel e b é a quantidade de filtros) 
                                                                                                       # Então o output da convolução será: n x (s-a+1) x b
model_middle.add(tf.keras.layers.Flatten()) # Esta camada remove a dimensão extra, transformando um tensor de tamanho n x 399 x 1 em um tensor de tamanho n x 399


optimizer = tf.keras.optimizers.Adam(learning_rate=10**-1, beta_1=0.9, beta_2=0.999, clipnorm=1.0)
model_middle.compile(loss='mean_squared_error',optimizer=optimizer,metrics=['mean_squared_error'])

In [10]:
history = model_middle.fit(train_x, train_y[:,1:-1], # Como estamos calculando a derivada centrada, devemos remover a primeira e a última derivada
                    batch_size=512,
                    epochs=30,
                    validation_split=0.2)
test_scores = model_middle.evaluate(test_x, test_y[:,1:-1], verbose=1)
print('Test loss:', test_scores[0])
print('Test accuracy:', test_scores[1])

Epoch 1/30
63/63 [==============================] - 1s 9ms/step - loss: 489.1279 - mean_squared_error: 489.1279 - val_loss: 427.3027 - val_mean_squared_error: 427.3027
Epoch 2/30
63/63 [==============================] - 0s 6ms/step - loss: 370.9158 - mean_squared_error: 370.9158 - val_loss: 317.3097 - val_mean_squared_error: 317.3097
Epoch 3/30
63/63 [==============================] - 0s 6ms/step - loss: 269.1168 - mean_squared_error: 269.1168 - val_loss: 223.6654 - val_mean_squared_error: 223.6654
Epoch 4/30
63/63 [==============================] - 0s 6ms/step - loss: 184.0123 - mean_squared_error: 184.0123 - val_loss: 146.3653 - val_mean_squared_error: 146.3653
Epoch 5/30
63/63 [==============================] - 0s 6ms/step - loss: 114.5868 - mean_squared_error: 114.5868 - val_loss: 85.4078 - val_mean_squared_error: 85.4078
Epoch 6/30
63/63 [==============================] - 0s 6ms/step - loss: 61.8480 - mean_squared_error: 61.8480 - val_loss: 40.7924 - val_mean_squared_error: 40.792

In [11]:
# Pegando os pesos da segunda camada (a de convolução) da rede e multiplicando por Δx para ver se o valor está correto (o ideal seria -0.5, 0 e 0.5).
model_middle.layers[1].weights[0]*Δx

<tf.Tensor: shape=(3, 1, 1), dtype=float32, numpy=
array([[[-0.5182046 ]],

       [[-0.00181072]],

       [[ 0.5201305 ]]], dtype=float32)>

### De maneira geral, os resultados foram satisfatórios, lembrando que o conjunto de dados é relativamente pequeno (50.000 observações), então é natural que a rede não consiga encontrar os pesos exatos devido a algum viés aleatório do conjunto de treino.
### Fica a critério do usuário aumentar o tamanho do conjunto de treino afim de gerar aproximações melhores.